### ISSUE TITLE
start-beacon-node.sh mismatch with recent lighthouse release: "--max-skip-slots" flag currently not implemented in lighthouse

### ISSUE THREAD

**Issue by jpitts** [sigp/lighthouse-docker#16]
This commit https://github.com/sigp/lighthouse-docker/commit/6545d67d64fb7e6d1df3b138dc9fb1fbf9fda766 adds the following flag: 

```
--max-skip-slots 700 
```

However, this flag breaks the "sigp/lighthouse:latest" released to DockerHub. 

![image](https://user-images.githubusercontent.com/509756/91331180-4c964200-e77f-11ea-8aa8-8249e76fe900.png)

Three suggestions:
- improved versioning and releases of lighthouse to DockerHub, perhaps even with coordination 
- the docker-compose.yml in lighthouse-docker could specify the exact tagged docker image
- synchronization of versioning / tagging of lighthouse-docker in GitHub, versioning of lighthouse client in Github, and versioning on DockerHub

**Comment by jpitts** [comment]
The reason is that running "docker-compose up" does not fetch the latest latest, rather the latest when I first set it up.

```
sudo docker run sigp/lighthouse:latest lighthouse --version
Lighthouse v0.2.1-b354a83f+
```

```
sudo docker-compose pull
Pulling beacon_node (sigp/lighthouse:latest)...
latest: Pulling from sigp/lighthouse
bf5952930446: Already exists
de5c19cbb066: Pull complete
4e56c9c1d003: Pull complete
e553ed863c1a: Pull complete
Digest: sha256:6d66ff0b4494ff39a292e05a2a9b16d209087056daaeed9709ff6c5031948bd5
Status: Downloaded newer image for sigp/lighthouse:latest
Pulling validator_client (sigp/lighthouse:latest)...
latest: Pulling from sigp/lighthouse
Digest: sha256:6d66ff0b4494ff39a292e05a2a9b16d209087056daaeed9709ff6c5031948bd5
Status: Image is up to date for sigp/lighthouse:latest
```

This did the trick, now it runs w/ the "--max-skip-slots 700".

**Comment by kvbik** [comment]
Basically the problem is with pinning of versions of the docker images. But it seems like docker images for lighthouse are now just `latest` which has the version from `master`, right?

**Comment by AgeManning** [comment]
Yep, latest gets updated by CI every time we push to master. 

The docker compose should be coordinated with releases so that if the image is updated every time I release comes there should be no conflicts.
