### ISSUE TITLE
Makefile:7: recipe for target 'repo' failed

### ISSUE THREAD

**Issue by prestonvanloon** [sigp/lighthouse-docker#2]
To reproduce, I checked out this repo and ran `make`. 

```
Successfully built 359ec2a8b7d1
Successfully tagged lighthouse-builder:latest
docker run --mount type=bind,source="/tmp/lighthouse-docker"/lighthouse/repo,target=/root/lighthouse --mount type=bind,source="/tmp/lighthouse-docker"/lighthouse/cargo-cache,target=/root/.cargo lighthouse-builder
error: could not find `Cargo.toml` in `/root/lighthouse` or any parent directory
Makefile:7: recipe for target 'repo' failed
make: *** [repo] Error 101
```

**Comment by TrevorJTClarke** [comment]
@prestonvanloon I ran into this as well, I setup changes in PR #3 .
Can you try the submodule cmd: `git submodule update --init` then do the `make` step?
I'm hoping you had the same issue :)

**Comment by prestonvanloon** [comment]
@TrevorJTClarke That's probably my issue. I jumped to `To start the enviroment, run` and thought it would just work. I'll give it another try later.

**Comment by adaszko** [comment]
Looks like the `Makefile` has been removed in fb54801d25f8c5532e03c0fafe0719c35aec9092, so I think issues can be closed now.
