### ISSUE TITLE
Update to v1

### ISSUE THREAD

**Issue by pscott** [sigp/lighthouse-docker#43]
Lighthouse recently updated to v1, but it looks like this repo hasn't yet been properly updated.

Current issues are :

- `--testnet` flag has been changed to `--network`.
- testnet still defaults to medalla whereas latest testnet should be pyrmont.
- Update "allowed values" for testnet in default-env file.

**Comment by pscott** [comment]
Corresponding PR: #42

**Comment by hukkinj1** [comment]
@AgeManning understandably you all must be very busy right now, but do you think someone from sigp would have the time to review the open PRs and give an approval of v1 / mainnet compatibility to this repo before mainnet launch? Would be much appreciated :smiley_cat:

**Comment by AgeManning** [comment]
Yep, am getting to them :)

**Comment by AgeManning** [comment]
I've got to the main ones I think. I'm going to close this guy
