### ISSUE TITLE
Add --auto-register on next Lighthouse update

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse-docker#6]
The validator client should be run with `--auto-register`, once https://github.com/sigp/lighthouse/pull/1116 is merged and lighthouse-docker is updated.

It should be as simple as adding it here:

https://github.com/sigp/lighthouse-docker/blob/c9daa37295d518f97cd7faebbb25b9a92619cc35/scripts/start-validator-client.sh#L14-L17

**Comment by paulhauner** [comment]
Thank you for updating the docs _and_ thinking of this repo <3
